behaviors:
  CherryBot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 3000000
    time_horizon: 256
    summary_freq: 15000
    checkpoint_interval: 150000

#to view results
#tensorboard --logdir results

#run training from a build and see the training, builds5/CheryBot.exe is the path
# mlagents-learn config.yaml --run-id=TestFINALENEW --env=builds5/CheryBot.exe --width=1900 --height=1080 --resume

#THE FASTEST run training from a build without graphics 4xfaster
#mlagents-learn config.yaml --run-id=TestFINALENEW --env=builds5/CheryBot.exe --no-graphics --num-envs=4 --resume